name: Test_Parking_Application

# Triggers: launch workflow when pushing in branch main and Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Clone repository
    - name: 1. Clone repository
      uses: actions/checkout@v3

    # 2. Install Python
    - name: 2. Set up Python 3.14.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.14.2"

    # 3. Install dependencies 
    - name: 3. Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Launch tests with Pytest
    # Flag -v enables verbose output
    - name: 4. Launch test with pytest
      run: |
        pytest -v
